### PR TITLE
chore: devcontainer fixes

### PR DESCRIPTION
**Pull request by andreas-kurz**
- allow hotplug for all devices in the devcontainer
- show the whole workspace folder in the file explorer
- adds bash completion to the container

### CODE REVIEW

**Review by rexut — DISMISSED** [review]
LGTM, thanks

**Comment by andreas-kurz** [comment]
@rexut 

Could you re-approve this PR? Wasn't able to merge it as Github seemed to be confused with rebasing the signed commits – don't know.

I also bumped the container version to the latest release :)

**Review by tobiaskaestner — APPROVED** [review]
LGTM

**Review by rexut — DISMISSED** [review]
LGTM

**Comment by andreas-kurz** [comment]
OK ... so what am I doing wrong. The only merge option i have from github si "Rebase and merge" which fails all the time because github can't "Rebase and merge" for me. The branch is rebased on main :cry:

**Comment by rexut** [comment]
> OK ... so what am I doing wrong. The only merge option i have from github si "Rebase and merge" which fails all the time because github can't "Rebase and merge" for me. The branch is rebased on main 😢

@andreas-kurz you have to merge (fast forward) locally and push as long as the main branch is protected to allow verified commits only – call me, if you need help

**Review by rexut — APPROVED** [review]
LGTM, thanks

**Pull request merged**
