### PR TITLE
Drivers for NXP SC18IS604 SPI to I2C/GPIO bridge

### LINKED ISSUE #247: [HW] NXP SC18IS604 SPI to I2C bridge
We need support for the NXP SC18IS604 SPI to I2C bridge.

**Describe why you are asking for this support?**
There is no upstream Zephyr driver for this chip.

### PR DESCRIPTION
**Pull request by Irockasingranite**
Adds drivers for the NXP SC18IS604 MFD, which provides an I2C bus and several (interrupt-less) GPIOs pins over SPI.

Closes #247.

### CODE REVIEW

**Review by tobiaskaestner — COMMENTED** [review]
Could we add a simple sample or implement our version of the all drivers test case that exists upstream?

**Comment by rexut** [comment]
> Could we add a simple sample or implement our version of the all drivers test case that exists upstream?

I'll add this, good idea.

Also I'll define a merge order in relation to the other outstanding PR #248:

1. first merge: this PR #249
2. second merge (then rebased to the first one): the other PR #248

**Review by rexut — APPROVED** [review]
@tobiaskaestner now, we use the Zephyr upstream tests for build all drivers.

**Review by tobiaskaestner — APPROVED** [review]
Lgtm, many thanks

**Pull request merged**
