### PR TITLE
Add devcontainer integration for vscode

### PR DESCRIPTION
**Pull request by andreas-kurz**
This will auto setup the whole build environment based on zephyr's docker containers. Prerequisites are:
- docker is accessable by the user without using sudo
- vscode with remote container extension is installed

Create a directory for your workspace. Go into that directory and clone the bridle repo.
Open the repo folder in vscode and select from the commands "Dev Containers: Reopen in container" (you might be prompted in the bottom right corner for that).

This will then download the docker container, install packages etc. so that you can directly start with a `west build`

### CODE REVIEW

**Comment by rexut** [comment]
@andreas-kurz Please, could you add your signed-off in the commit message and fix our QA Compliance Check:

```
ERROR   : Test Identity failed: 
28e54b00f69ffc46617591d9125058e967937f0c: author email (Andreas Kurz <andreas.kurz@methodpark.de>) needs to match one of the signed-off-by entries.
```

**Comment by andreas-kurz** [comment]
> @andreas-kurz Please, could you add your signed-off in the commit message and fix our QA Compliance Check:
> 
> ```
> ERROR   : Test Identity failed: 
> 28e54b00f69ffc46617591d9125058e967937f0c: author email (Andreas Kurz <andreas.kurz@methodpark.de>) needs to match one of the signed-off-by entries.
> ```

Sorry, seems like I forgot to add the ul address to my GPG key. And somehow my git commit didn't add the "signed-off by" to the message. Should be fixed now

**Review by rexut — APPROVED** [review]
LGTM, many thanks.

**Comment by rexut** [comment]
> > @andreas-kurz Please, could you add your signed-off in the commit message and fix our QA Compliance Check:
> > ```
> > ERROR   : Test Identity failed: 
> > 28e54b00f69ffc46617591d9125058e967937f0c: author email (Andreas Kurz <andreas.kurz@methodpark.de>) needs to match one of the signed-off-by entries.
> > ```
> 
> Sorry, seems like I forgot to add the ul address to my GPG key. And somehow my git commit didn't add the "signed-off by" to the message. Should be fixed now

No problem. The signed-off was more important than missed GPG keys. No I was able to rebase and sign by me. All fine, thnx.

**Pull request merged**
