### PR TITLE
Enable documentation rebuilds for v2.7 on main

### LINKED ISSUE #49: Can't rebuild documentation
```
Exception occurred:
  File "/home/runner/.local/lib/python3.8/site-packages/west/manifest.py", line 1417, in get_projects
    raise ValueError(unknown, uncloned)
ValueError: (['bridle'], [])
The full traceback has been saved in /tmp/sphinx-err-6o4drt8w.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
FAILED: CMakeFiles/bridle-html-all /home/runner/work/bridle/bridle/workspace/build/CMakeFiles/bridle-html-all 
```

### PR DESCRIPTION
**Pull request by rexut**
fix #49

### CODE REVIEW

**Comment by rexut** [comment]
Have a look on the documentation --> https://bridle.tiac-systems.net/ghpr/doc/PR-52/

**Comment by rexut** [comment]
image

**Review by tobiaskaestner — DISMISSED** [review]

**Comment by rexut** [comment]
Should not yet merged. The CI fails on all integration tests --> https://github.com/tiacsys/bridle/runs/5598814265?check_suite_focus=true#step:8:1290

**Comment by rexut** [comment]
We lost some style sheets in HTML --> evaluate (and fix on demand) the private CSS overwrites against the original oen from RTD theme / Zephyr theme:

image

**Review by tobiaskaestner — APPROVED** [review]
Looks all good to me, many thanks

**Pull request merged**
