### PR TITLE
Introduce Bridle versioning

### PR DESCRIPTION
**Pull request by rexut**
- set up out of tree arch, boards, samples, tests
- set up Bridle versioning
- define Bridle version: 0.2.5.99-main
- Bridle commands now as sub-system for shell (refactoring source code)
- Bridle API provides BRIDLEVERSION
- Bridle command for long and short version (short is default)
- Bridle information command with version strings
- Bridle common integration tests, start with version
- run Bridle common integration tests on GitHub CI Actions

related to issue #30

### CODE REVIEW

**Comment by rexut** [comment]
Now, the documentation has to expand with the new integration test(s).

**Comment by rexut** [comment]
The documentation needs a quick overview about the intended and planned branch strategy, a simple graphic would be enough for starting.

**Comment by rexut** [comment]
> * [ ]  The documentation needs a quick overview about the intended and planned branch strategy. A simple graphic in section "Development model" would be enough for starting.
> * [x]  Also would be nice to see a first API section similar to Zephyr's one, see: https://tiacsys.github.io/bridle/zephyr/reference/kernel/other/version.html

https://github.com/tiacsys/bridle/pull/31/commits/70c1122f3bac5082cd0b18073c61a3980365ee90

**Review by tobiaskaestner — APPROVED** [review]
This is a huge PR and in that regard probably an exception to get things going. For future PRs we should really strive for smaller changesets and fewer commits to allow for efficient reviews.

**Pull request merged**
